set_property PACKAGE_PIN D19 [get_ports a]
set_property PACKAGE_PIN D20 [get_ports b]
set_property PACKAGE_PIN L15 [get_ports y]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports y]
