set_property SRC_FILE_INFO {cfile:{C:/Users/Admin/Vivado_Udemy/Design Flow Part 1/project_1/project_1.srcs/constrs_1/new/custom_proj1_XDC.xdc} rfile:../../../project_1.srcs/constrs_1/new/custom_proj1_XDC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports a]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports b]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports y]
